#!/usr/bin/env python3
"""Phase 1: Database types, auth actions, proxy with roles."""

import os

BASE = "/Users/alexisgarcia/foodlytics/src"

def w(rel_path, lines):
    full = os.path.join(BASE, rel_path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"  {rel_path}")

# ── Database Types ──────────────────────────────────────────────
w("types/database.ts", [
    'export type UserRole = "client" | "nutritionist" | "trainer" | "admin";',
    '',
    'export interface Profile {',
    '  id: string;',
    '  email: string | null;',
    '  full_name: string | null;',
    '  role: UserRole;',
    '  phone: string | null;',
    '  avatar_url: string | null;',
    '  created_at: string;',
    '  updated_at: string;',
    '}',
    '',
    'export interface Client {',
    '  id: string;',
    '  user_id: string;',
    '  age: number | null;',
    '  sex: string | null;',
    '  weight: number | null;',
    '  height: number | null;',
    '  goal: string | null;',
    '  activity_level: string | null;',
    '  created_at: string;',
    '  updated_at: string;',
    '}',
    '',
    'export interface Nutritionist {',
    '  id: string;',
    '  user_id: string;',
    '  specialty: string | null;',
    '  license_number: string | null;',
    '  experience_years: number | null;',
    '  bio: string | null;',
    '  created_at: string;',
    '  updated_at: string;',
    '}',
    '',
    'export interface Trainer {',
    '  id: string;',
    '  user_id: string;',
    '  specialty: string | null;',
    '  certifications: string | null;',
    '  experience_years: number | null;',
    '  bio: string | null;',
    '  created_at: string;',
    '  updated_at: string;',
    '}',
    '',
    'export interface MealPlan {',
    '  id: string;',
    '  nutritionist_id: string;',
    '  client_id: string | null;',
    '  name: string;',
    '  description: string | null;',
    '  daily_calories: number | null;',
    '  is_template: boolean;',
    '  created_at: string;',
    '  updated_at: string;',
    '}',
    '',
    'export interface Meal {',
    '  id: string;',
    '  meal_plan_id: string;',
    '  meal_type: string;',
    '  name: string;',
    '  description: string | null;',
    '  calories: number | null;',
    '  protein: number | null;',
    '  carbs: number | null;',
    '  fat: number | null;',
    '  time: string | null;',
    '  created_at: string;',
    '}',
    '',
    'export interface Exercise {',
    '  id: string;',
    '  name: string;',
    '  description: string | null;',
    '  muscle_group: string | null;',
    '  equipment: string | null;',
    '  difficulty: string | null;',
    '  created_at: string;',
    '}',
    '',
    'export interface Routine {',
    '  id: string;',
    '  trainer_id: string;',
    '  client_id: string | null;',
    '  name: string;',
    '  description: string | null;',
    '  is_template: boolean;',
    '  created_at: string;',
    '  updated_at: string;',
    '}',
    '',
    'export interface RoutineExercise {',
    '  id: string;',
    '  routine_id: string;',
    '  exercise_id: string;',
    '  sets: number | null;',
    '  reps: number | null;',
    '  rest_time: string | null;',
    '  order_index: number;',
    '  created_at: string;',
    '}',
    '',
    'export interface ClientProgress {',
    '  id: string;',
    '  client_id: string;',
    '  weight: number | null;',
    '  body_fat: number | null;',
    '  chest: number | null;',
    '  waist: number | null;',
    '  hips: number | null;',
    '  arm: number | null;',
    '  thigh: number | null;',
    '  notes: string | null;',
    '  photo_url: string | null;',
    '  recorded_at: string;',
    '  created_at: string;',
    '}',
    '',
    'export interface Appointment {',
    '  id: string;',
    '  professional_id: string;',
    '  client_id: string;',
    '  title: string;',
    '  description: string | null;',
    '  date: string;',
    '  time: string;',
    '  duration_minutes: number;',
    '  status: string;',
    '  type: string;',
    '  created_at: string;',
    '  updated_at: string;',
    '}',
    '',
    'export interface Message {',
    '  id: string;',
    '  sender_id: string;',
    '  receiver_id: string;',
    '  content: string;',
    '  read: boolean;',
    '  created_at: string;',
    '}',
    '',
    'export interface Payment {',
    '  id: string;',
    '  professional_id: string;',
    '  client_id: string;',
    '  amount: number;',
    '  currency: string;',
    '  status: string;',
    '  payment_date: string;',
    '  due_date: string | null;',
    '  description: string | null;',
    '  created_at: string;',
    '}',
    '',
    'export interface ExerciseVideo {',
    '  id: string;',
    '  exercise_id: string;',
    '  title: string;',
    '  video_url: string;',
    '  created_at: string;',
    '}',
])

# ── Role utility ─────────────────────────────────────────────────
w("lib/roles.ts", [
    'import { createClient } from "@/lib/supabase/server";',
    'import { redirect } from "next/navigation";',
    'import type { UserRole } from "@/types/database";',
    '',
    'export async function getCurrentUser() {',
    '  const supabase = await createClient();',
    '  const { data: { user }, error } = await supabase.auth.getUser();',
    '  if (error || !user) return null;',
    '  return user;',
    '}',
    '',
    'export async function requireUser() {',
    '  const user = await getCurrentUser();',
    '  if (!user) redirect("/login");',
    '  return user;',
    '}',
    '',
    'export async function getUserRole(): Promise<UserRole | null> {',
    '  const user = await getCurrentUser();',
    '  if (!user) return null;',
    '  const role = user.user_metadata?.role as UserRole | undefined;',
    '  if (role && ["client", "nutritionist", "trainer", "admin"].includes(role)) {',
    '    return role;',
    '  }',
    '  return "client";',
    '}',
    '',
    'export async function requireRole(allowedRoles: UserRole[]) {',
    '  const user = await requireUser();',
    '  const role = await getUserRole();',
    '  if (!role || !allowedRoles.includes(role)) {',
    '    redirect("/login");',
    '  }',
    '  return { user, role };',
    '}',
    '',
    'export function getRoleDashboard(role: UserRole): string {',
    '  const dashboards: Record<UserRole, string> = {',
    '    client: "/client/dashboard",',
    '    nutritionist: "/nutritionist/dashboard",',
    '    trainer: "/trainer/dashboard",',
    '    admin: "/admin/dashboard",',
    '  };',
    '  return dashboards[role];',
    '}',
])

# ── Auth Actions ────────────────────────────────────────────────
w("app/actions/auth.ts", [
    '"use server";',
    '',
    'import { createClient } from "@/lib/supabase/server";',
    'import { redirect } from "next/navigation";',
    'import { getRoleDashboard } from "@/lib/roles";',
    'import type { UserRole } from "@/types/database";',
    '',
    'export async function login(_prev: unknown, formData: FormData) {',
    '  const supabase = await createClient();',
    '',
    '  const email = formData.get("email") as string;',
    '  const password = formData.get("password") as string;',
    '',
    '  if (!email || !password) {',
    '    return { error: "Email and password are required." };',
    '  }',
    '',
    '  const { data, error } = await supabase.auth.signInWithPassword({',
    '    email,',
    '    password,',
    '  });',
    '',
    '  if (error) {',
    '    return { error: error.message };',
    '  }',
    '',
    '  const role = data.user?.user_metadata?.role as UserRole | undefined;',
    '  if (role && role !== "client") {',
    '    redirect(getRoleDashboard(role));',
    '  }',
    '  redirect("/client/dashboard");',
    '}',
    '',
    'export async function signup(_prev: unknown, formData: FormData) {',
    '  const supabase = await createClient();',
    '',
    '  const email = formData.get("email") as string;',
    '  const password = formData.get("password") as string;',
    '  const fullName = formData.get("full_name") as string;',
    '  const role = formData.get("role") as UserRole;',
    '',
    '  if (!email || !password) {',
    '    return { error: "Email and password are required." };',
    '  }',
    '',
    '  if (!role || !["client", "nutritionist", "trainer"].includes(role)) {',
    '    return { error: "Please select a valid role." };',
    '  }',
    '',
    '  const { data, error } = await supabase.auth.signUp({',
    '    email,',
    '    password,',
    '    options: {',
    '      data: {',
    '        full_name: fullName,',
    '        role: role,',
    '      },',
    '    },',
    '  });',
    '',
    '  if (error) {',
    '    return { error: error.message };',
    '  }',
    '',
    '  if (data.user?.identities?.length === 0) {',
    '    return { success: "An account with this email already exists. Please sign in." };',
    '  }',
    '',
    '  redirect("/login?registered=true");',
    '}',
    '',
    'export async function logout() {',
    '  const supabase = await createClient();',
    '  await supabase.auth.signOut();',
    '  redirect("/login");',
    '}',
])

# ── Proxy (middleware) with role redirect ────────────────────────
proxy_lines = []
proxy_lines.append('import { type NextRequest, NextResponse } from "next/server";')
proxy_lines.append('import { createServerClient } from "@supabase/ssr";')
proxy_lines.append('')
proxy_lines.append('const ROLE_ROUTES: Record<string, string> = {')
proxy_lines.append('  client: "/client/dashboard",')
proxy_lines.append('  nutritionist: "/nutritionist/dashboard",')
proxy_lines.append('  trainer: "/trainer/dashboard",')
proxy_lines.append('  admin: "/admin/dashboard",')
proxy_lines.append('};')
proxy_lines.append('')
proxy_lines.append('export async function proxy(request: NextRequest) {')
proxy_lines.append('  let supabaseResponse = NextResponse.next({ request });')
proxy_lines.append('  const supabase = createServerClient(')
proxy_lines.append('    process.env.NEXT_PUBLIC_SUPABASE_URL!,')
proxy_lines.append('    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,')
proxy_lines.append('    {')
proxy_lines.append('      cookies: {')
proxy_lines.append('        getAll() { return request.cookies.getAll(); },')
proxy_lines.append('        setAll(cookiesToSet) {')
proxy_lines.append('          cookiesToSet.forEach(({ name, value }) => request.cookies.set(name, value));')
proxy_lines.append('          supabaseResponse = NextResponse.next({ request });')
proxy_lines.append('          cookiesToSet.forEach(({ name, value, options }) => supabaseResponse.cookies.set(name, value, options));')
proxy_lines.append('        },')
proxy_lines.append('      },')
proxy_lines.append('    },')
proxy_lines.append('  );')
proxy_lines.append('')
proxy_lines.append('  const { data: { user } } = await supabase.auth.getUser();')
proxy_lines.append('  const { pathname } = request.nextUrl;')
proxy_lines.append('')
proxy_lines.append('  // Allow public routes')
proxy_lines.append('  const publicRoutes = ["/login", "/signup", "/", "/auth/", "/_next/"];')
proxy_lines.append('  const isPublic = publicRoutes.some(r => pathname.startsWith(r));')
proxy_lines.append('')
proxy_lines.append('  // Redirect authenticated users away from public routes')
proxy_lines.append('  if (user && (pathname === "/login" || pathname === "/signup")) {')
proxy_lines.append('    const role = user.user_metadata?.role as string || "client";')
proxy_lines.append('    const dashboard = ROLE_ROUTES[role] || "/client/dashboard";')
proxy_lines.append('    const url = request.nextUrl.clone();')
proxy_lines.append('    url.pathname = dashboard;')
proxy_lines.append('    return NextResponse.redirect(url);')
proxy_lines.append('  }')
proxy_lines.append('')
proxy_lines.append('  // Redirect unauthenticated users away from protected routes')
proxy_lines.append('  if (!user && !isPublic && pathname !== "/") {')
proxy_lines.append('    const url = request.nextUrl.clone();')
proxy_lines.append('    url.pathname = "/login";')
proxy_lines.append('    return NextResponse.redirect(url);')
proxy_lines.append('  }')
proxy_lines.append('')
proxy_lines.append('  // Role-based route protection')
proxy_lines.append('  if (user) {')
proxy_lines.append('    const role = user.user_metadata?.role as string || "client";')
proxy_lines.append('    if (pathname.startsWith("/client/") && role !== "client" && role !== "admin") {')
proxy_lines.append('      const url = request.nextUrl.clone();')
proxy_lines.append('      url.pathname = ROLE_ROUTES[role] || "/login";')
proxy_lines.append('      return NextResponse.redirect(url);')
proxy_lines.append('    }')
proxy_lines.append('    if (pathname.startsWith("/nutritionist/") && role !== "nutritionist" && role !== "admin") {')
proxy_lines.append('      const url = request.nextUrl.clone();')
proxy_lines.append('      url.pathname = ROLE_ROUTES[role] || "/login";')
proxy_lines.append('      return NextResponse.redirect(url);')
proxy_lines.append('    }')
proxy_lines.append('    if (pathname.startsWith("/trainer/") && role !== "trainer" && role !== "admin") {')
proxy_lines.append('      const url = request.nextUrl.clone();')
proxy_lines.append('      url.pathname = ROLE_ROUTES[role] || "/login";')
proxy_lines.append('      return NextResponse.redirect(url);')
proxy_lines.append('    }')
proxy_lines.append('    if (pathname.startsWith("/admin/") && role !== "admin") {')
proxy_lines.append('      const url = request.nextUrl.clone();')
proxy_lines.append('      url.pathname = "/login";')
proxy_lines.append('      return NextResponse.redirect(url);')
proxy_lines.append('    }')
proxy_lines.append('    // Redirect /dashboard to role-specific')
proxy_lines.append('    if (pathname === "/dashboard" || pathname === "/dashboard/") {')
proxy_lines.append('      const url = request.nextUrl.clone();')
proxy_lines.append('      url.pathname = ROLE_ROUTES[role] || "/client/dashboard";')
proxy_lines.append('      return NextResponse.redirect(url);')
proxy_lines.append('    }')
proxy_lines.append('  }')
proxy_lines.append('')
proxy_lines.append('  return supabaseResponse;')
proxy_lines.append('}')
proxy_lines.append('')
proxy_lines.append('export const config = {')
proxy_lines.append('  matcher: [')
proxy_lines.append('    "/((?!_next/static|_static|_next/image|favicon.ico|.*\\\\\\\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)",')
proxy_lines.append('  ],')
proxy_lines.append('};')
w("proxy.ts", proxy_lines)

# ── SQL Migration ────────────────────────────────────────────────
migrations_base = "/Users/alexisgarcia/foodlytics/supabase/migrations"
w("../../supabase/migrations/001_roles_schema.sql", [
    '-- Create enum type for user roles',
    "CREATE TYPE user_role AS ENUM ('client', 'nutritionist', 'trainer', 'admin');",
    '',
    '-- Update profiles table to include role',
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS role user_role NOT NULL DEFAULT 'client';",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS phone text;",
    '',
    '-- Clients table',
    'CREATE TABLE IF NOT EXISTS clients (',
    '  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),',
    '  user_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL UNIQUE,',
    '  age integer,',
    '  sex text,',
    '  weight numeric(5,2),',
    '  height numeric(5,2),',
    '  goal text,',
    '  activity_level text,',
    '  created_at timestamptz DEFAULT now(),',
    '  updated_at timestamptz DEFAULT now()',
    ');',
    '',
    '-- Nutritionists table',
    'CREATE TABLE IF NOT EXISTS nutritionists (',
    '  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),',
    '  user_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL UNIQUE,',
    '  specialty text,',
    '  license_number text,',
    '  experience_years integer,',
    '  bio text,',
    '  created_at timestamptz DEFAULT now(),',
    '  updated_at timestamptz DEFAULT now()',
    ');',
    '',
    '-- Trainers table',
    'CREATE TABLE IF NOT EXISTS trainers (',
    '  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),',
    '  user_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL UNIQUE,',
    '  specialty text,',
    '  certifications text,',
    '  experience_years integer,',
    '  bio text,',
    '  created_at timestamptz DEFAULT now(),',
    '  updated_at timestamptz DEFAULT now()',
    ');',
    '',
    '-- Meal plans table',
    'CREATE TABLE IF NOT EXISTS meal_plans (',
    '  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),',
    '  nutritionist_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,',
    '  client_id uuid REFERENCES clients(id) ON DELETE SET NULL,',
    '  name text NOT NULL,',
    '  description text,',
    '  daily_calories integer,',
    '  is_template boolean DEFAULT false,',
    '  created_at timestamptz DEFAULT now(),',
    '  updated_at timestamptz DEFAULT now()',
    ');',
    '',
    '-- Meals table',
    'CREATE TABLE IF NOT EXISTS meals (',
    '  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),',
    '  meal_plan_id uuid REFERENCES meal_plans(id) ON DELETE CASCADE NOT NULL,',
    '  meal_type text NOT NULL,',
    '  name text NOT NULL,',
    '  description text,',
    '  calories integer,',
    '  protein numeric(5,1),',
    '  carbs numeric(5,1),',
    '  fat numeric(5,1),',
    '  time time,',
    '  created_at timestamptz DEFAULT now()',
    ');',
    '',
    '-- Exercises table',
    'CREATE TABLE IF NOT EXISTS exercises (',
    '  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),',
    '  name text NOT NULL,',
    '  description text,',
    '  muscle_group text,',
    '  equipment text,',
    '  difficulty text,',
    '  created_at timestamptz DEFAULT now()',
    ');',
    '',
    '-- Training routines table',
    'CREATE TABLE IF NOT EXISTS routines (',
    '  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),',
    '  trainer_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,',
    '  client_id uuid REFERENCES clients(id) ON DELETE SET NULL,',
    '  name text NOT NULL,',
    '  description text,',
    '  is_template boolean DEFAULT false,',
    '  created_at timestamptz DEFAULT now(),',
    '  updated_at timestamptz DEFAULT now()',
    ');',
    '',
    '-- Routine exercises join table',
    'CREATE TABLE IF NOT EXISTS routine_exercises (',
    '  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),',
    '  routine_id uuid REFERENCES routines(id) ON DELETE CASCADE NOT NULL,',
    '  exercise_id uuid REFERENCES exercises(id) ON DELETE CASCADE NOT NULL,',
    '  sets integer,',
    '  reps integer,',
    '  rest_time text,',
    '  order_index integer NOT NULL DEFAULT 0,',
    '  created_at timestamptz DEFAULT now()',
    ');',
    '',
    '-- Client progress table',
    'CREATE TABLE IF NOT EXISTS client_progress (',
    '  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),',
    '  client_id uuid REFERENCES clients(id) ON DELETE CASCADE NOT NULL,',
    '  weight numeric(5,2),',
    '  body_fat numeric(5,2),',
    '  chest numeric(5,2),',
    '  waist numeric(5,2),',
    '  hips numeric(5,2),',
    '  arm numeric(5,2),',
    '  thigh numeric(5,2),',
    '  notes text,',
    '  photo_url text,',
    '  recorded_at date DEFAULT CURRENT_DATE,',
    '  created_at timestamptz DEFAULT now()',
    ');',
    '',
    '-- Appointments table',
    'CREATE TABLE IF NOT EXISTS appointments (',
    '  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),',
    '  professional_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,',
    '  client_id uuid REFERENCES clients(id) ON DELETE CASCADE NOT NULL,',
    '  title text NOT NULL,',
    '  description text,',
    '  date date NOT NULL,',
    '  time time NOT NULL,',
    '  duration_minutes integer DEFAULT 30,',
    "  status text DEFAULT 'scheduled',",
    '  type text NOT NULL,',
    '  created_at timestamptz DEFAULT now(),',
    '  updated_at timestamptz DEFAULT now()',
    ');',
    '',
    '-- Messages table',
    'CREATE TABLE IF NOT EXISTS messages (',
    '  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),',
    '  sender_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,',
    '  receiver_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,',
    '  content text NOT NULL,',
    '  read boolean DEFAULT false,',
    '  created_at timestamptz DEFAULT now()',
    ');',
    '',
    '-- Payments table',
    'CREATE TABLE IF NOT EXISTS payments (',
    '  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),',
    '  professional_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,',
    '  client_id uuid REFERENCES clients(id) ON DELETE CASCADE NOT NULL,',
    '  amount numeric(10,2) NOT NULL,',
    "  currency text DEFAULT 'MXN',",
    "  status text DEFAULT 'pending',",
    '  payment_date timestamptz,',
    '  due_date date,',
    '  description text,',
    '  created_at timestamptz DEFAULT now()',
    ');',
    '',
    '-- Exercise videos table',
    'CREATE TABLE IF NOT EXISTS exercise_videos (',
    '  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),',
    '  exercise_id uuid REFERENCES exercises(id) ON DELETE CASCADE NOT NULL,',
    '  title text NOT NULL,',
    '  video_url text NOT NULL,',
    '  created_at timestamptz DEFAULT now()',
    ');',
    '',
    '-- Recipes table (for nutritionists)',
    'CREATE TABLE IF NOT EXISTS recipes (',
    '  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),',
    '  nutritionist_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,',
    '  name text NOT NULL,',
    '  description text,',
    '  ingredients jsonb,',
    '  instructions text,',
    '  calories integer,',
    '  protein numeric(5,1),',
    '  carbs numeric(5,1),',
    '  fat numeric(5,1),',
    '  created_at timestamptz DEFAULT now()',
    ');',
    '',
    '-- Subscriptions table',
    'CREATE TABLE IF NOT EXISTS subscriptions (',
    '  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),',
    '  client_id uuid REFERENCES clients(id) ON DELETE CASCADE NOT NULL,',
    '  professional_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,',
    '  plan_name text NOT NULL,',
    '  amount numeric(10,2) NOT NULL,',
    "  currency text DEFAULT 'MXN',",
    "  status text DEFAULT 'active',",
    '  start_date date NOT NULL,',
    '  end_date date,',
    '  created_at timestamptz DEFAULT now()',
    ');',
    '',
    '-- Enable RLS on all tables',
    'ALTER TABLE clients ENABLE ROW LEVEL SECURITY;',
    'ALTER TABLE nutritionists ENABLE ROW LEVEL SECURITY;',
    'ALTER TABLE trainers ENABLE ROW LEVEL SECURITY;',
    'ALTER TABLE meal_plans ENABLE ROW LEVEL SECURITY;',
    'ALTER TABLE meals ENABLE ROW LEVEL SECURITY;',
    'ALTER TABLE exercises ENABLE ROW LEVEL SECURITY;',
    'ALTER TABLE routines ENABLE ROW LEVEL SECURITY;',
    'ALTER TABLE routine_exercises ENABLE ROW LEVEL SECURITY;',
    'ALTER TABLE client_progress ENABLE ROW LEVEL SECURITY;',
    'ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;',
    'ALTER TABLE messages ENABLE ROW LEVEL SECURITY;',
    'ALTER TABLE payments ENABLE ROW LEVEL SECURITY;',
    'ALTER TABLE exercise_videos ENABLE ROW LEVEL SECURITY;',
    'ALTER TABLE recipes ENABLE ROW LEVEL SECURITY;',
    'ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;',
    '',
    '-- Basic RLS policies',
    'CREATE POLICY users_see_own ON profiles FOR SELECT USING (auth.uid() = id);',
    'CREATE POLICY users_update_own ON profiles FOR UPDATE USING (auth.uid() = id);',
    '',
    'CREATE POLICY clients_see_own ON clients FOR SELECT USING (auth.uid() = user_id);',
    "CREATE POLICY professionals_see_clients ON clients FOR SELECT USING (",
    '  EXISTS (',
    "    SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('nutritionist', 'trainer')",
    '  )',
    ');',
    '',
    '-- Create trigger for updated_at',
    'CREATE OR REPLACE FUNCTION update_updated_at()',
    'RETURNS trigger AS $$',
    'BEGIN',
    '  NEW.updated_at = now();',
    '  RETURN NEW;',
    'END;',
    "$$ LANGUAGE plpgsql;",
    '',
    "CREATE TRIGGER clients_updated_at BEFORE UPDATE ON clients FOR EACH ROW EXECUTE FUNCTION update_updated_at();",
    "CREATE TRIGGER nutritionists_updated_at BEFORE UPDATE ON nutritionists FOR EACH ROW EXECUTE FUNCTION update_updated_at();",
    "CREATE TRIGGER trainers_updated_at BEFORE UPDATE ON trainers FOR EACH ROW EXECUTE FUNCTION update_updated_at();",
    "CREATE TRIGGER meal_plans_updated_at BEFORE UPDATE ON meal_plans FOR EACH ROW EXECUTE FUNCTION update_updated_at();",
    "CREATE TRIGGER routines_updated_at BEFORE UPDATE ON routines FOR EACH ROW EXECUTE FUNCTION update_updated_at();",
    "CREATE TRIGGER appointments_updated_at BEFORE UPDATE ON appointments FOR EACH ROW EXECUTE FUNCTION update_updated_at();",
])

print("\nPhase 1 complete: types, auth, proxy, SQL migration")