#!/usr/bin/env python3
"""Write all Foodlytics components and pages for the premium redesign."""

import os

BASE = "/Users/alexisgarcia/foodlytics/src"

def w(rel_path, lines):
    full = os.path.join(BASE, rel_path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"  {rel_path}")

# ── Theme Provider ─────────────────────────────────────────────
w("components/theme-provider.tsx", [
    '"use client";',
    '',
    'import { createContext, useContext, useEffect, useState } from "react";',
    '',
    'type Theme = "light" | "dark";',
    '',
    'const ThemeContext = createContext<{',
    '  theme: Theme;',
    '  toggleTheme: () => void;',
    '}>({',
    '  theme: "dark",',
    '  toggleTheme: () => {},',
    '});',
    '',
    'export function ThemeProvider({',
    '  children,',
    '}: {',
    '  children: React.ReactNode;',
    '}) {',
    '  const [theme, setTheme] = useState<Theme>("dark");',
    '  const [mounted, setMounted] = useState(false);',
    '',
    '  useEffect(() => {',
    '    setMounted(true);',
    '    const stored = localStorage.getItem("theme") as Theme | null;',
    '    const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;',
    '    setTheme(stored || (prefersDark ? "dark" : "light"));',
    '  }, []);',
    '',
    '  useEffect(() => {',
    '    if (!mounted) return;',
    '    const root = document.documentElement;',
    '    if (theme === "dark") {',
    '      root.classList.add("dark");',
    '    } else {',
    '      root.classList.remove("dark");',
    '    }',
    '    localStorage.setItem("theme", theme);',
    '  }, [theme, mounted]);',
    '',
    '  const toggleTheme = () => setTheme((p) => (p === "dark" ? "light" : "dark"));',
    '',
    '  if (!mounted) return <>{children}</>;',
    '',
    '  return (',
    '    <ThemeContext.Provider value={{ theme, toggleTheme }}>',
    '      {children}',
    '    </ThemeContext.Provider>',
    '  );',
    '}',
    '',
    'export function useTheme() {',
    '  return useContext(ThemeContext);',
    '}',
])

# ── Theme Toggle ──────────────────────────────────────────────
w("components/theme-toggle.tsx", [
    '"use client";',
    '',
    'import { Moon, Sun } from "lucide-react";',
    'import { useTheme } from "@/components/theme-provider";',
    '',
    'export function ThemeToggle() {',
    '  const { theme, toggleTheme } = useTheme();',
    '',
    '  return (',
    '    <button',
    '      onClick={toggleTheme}',
    '      className="relative inline-flex h-9 w-9 items-center justify-center rounded-lg border border-border bg-background/50 text-muted-foreground transition-all hover:bg-secondary hover:text-foreground"',
    '      aria-label="Toggle theme"',
    '    >',
    '      <Sun className="h-4 w-4 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />',
    '      <Moon className="absolute h-4 w-4 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />',
    '    </button>',
    '  );',
    '}',
])

# ── Header ──────────────────────────────────────────────────────
w("components/header.tsx", [
    '"use client";',
    '',
    'import Link from "next/link";',
    'import { ThemeToggle } from "@/components/theme-toggle";',
    'import { Leaf } from "lucide-react";',
    '',
    'export function Header() {',
    '  return (',
    '    <header className="fixed top-0 z-50 w-full border-b border-border/50 bg-background/80 backdrop-blur-xl">',
    '      <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">',
    '        <Link href="/" className="flex items-center gap-2">',
    '          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary">',
    '            <Leaf className="h-4 w-4 text-primary-foreground" />',
    '          </div>',
    '          <span className="text-lg font-bold tracking-tight">Foodlytics</span>',
    '        </Link>',
    '        <nav className="hidden items-center gap-8 md:flex">',
    '          <a href="#features" className="text-sm text-muted-foreground transition-colors hover:text-foreground">Features</a>',
    '          <a href="#pricing" className="text-sm text-muted-foreground transition-colors hover:text-foreground">Pricing</a>',
    '          <a href="#faq" className="text-sm text-muted-foreground transition-colors hover:text-foreground">FAQ</a>',
    '        </nav>',
    '        <div className="flex items-center gap-3">',
    '          <ThemeToggle />',
    '          <Link',
    '            href="/login"',
    '            className="hidden text-sm font-medium text-muted-foreground transition-colors hover:text-foreground sm:block"',
    '          >',
    '            Sign In',
    '          </Link>',
    '          <Link',
    '            href="/signup"',
    '            className="inline-flex h-9 items-center justify-center rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground shadow-lg shadow-primary/25 transition-all hover:opacity-90"',
    '          >',
    '            Get Started',
    '          </Link>',
    '        </div>',
    '      </div>',
    '    </header>',
    '  );',
    '}',
])

# ── Hero ────────────────────────────────────────────────────────
w("components/hero.tsx", [
    '"use client";',
    '',
    'import Link from "next/link";',
    'import { motion } from "framer-motion";',
    'import { ArrowRight, Sparkles } from "lucide-react";',
    '',
    'export function Hero() {',
    '  return (',
    '    <section className="relative flex min-h-[calc(100vh-4rem)] items-center justify-center overflow-hidden pt-16">',
    '      {/* Background gradient */}',
    '      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_center,hsl(142_76%_36%/0.15),transparent_70%)]" />',
    '      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,hsl(217_91%_60%/0.1),transparent_50%)]" />',
    '',
    '      <div className="relative z-10 mx-auto max-w-5xl px-4 text-center sm:px-6">',
    '        <motion.div',
    '          initial={{ opacity: 0, y: 20 }}',
    '          animate={{ opacity: 1, y: 0 }}',
    '          transition={{ duration: 0.5 }}',
    '        >',
    '          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-border bg-secondary/50 px-4 py-1.5 text-sm text-muted-foreground">',
    '            <Sparkles className="h-3.5 w-3.5 text-primary" />',
    '            AI-Powered Nutrition Tracking',
    '          </div>',
    '        </motion.div>',
    '',
    '        <motion.h1',
    '          initial={{ opacity: 0, y: 20 }}',
    '          animate={{ opacity: 1, y: 0 }}',
    '          transition={{ duration: 0.5, delay: 0.1 }}',
    '          className="text-5xl font-bold tracking-tight sm:text-6xl lg:text-7xl"',
    '        >',
    '          Track. Analyze.',
    '          <br />',
    '          <span className="gradient-text">Optimize.</span>',
    '        </motion.h1>',
    '',
    '        <motion.p',
    '          initial={{ opacity: 0, y: 20 }}',
    '          animate={{ opacity: 1, y: 0 }}',
    '          transition={{ duration: 0.5, delay: 0.2 }}',
    '          className="mx-auto mt-6 max-w-2xl text-lg text-muted-foreground"',
    '        >',
    '          Foodlytics helps you understand your nutrition with AI insights and personalized recommendations.',
    '        </motion.p>',
    '',
    '        <motion.div',
    '          initial={{ opacity: 0, y: 20 }}',
    '          animate={{ opacity: 1, y: 0 }}',
    '          transition={{ duration: 0.5, delay: 0.3 }}',
    '          className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row"',
    '        >',
    '          <Link',
    '            href="/signup"',
    '            className="group inline-flex h-12 items-center gap-2 rounded-xl bg-primary px-8 text-base font-medium text-primary-foreground shadow-xl shadow-primary/30 transition-all hover:opacity-90"',
    '          >',
    '            Get Started Free',
    '            <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />',
    '          </Link>',
    '          <Link',
    '            href="/login"',
    '            className="inline-flex h-12 items-center rounded-xl border border-input bg-secondary px-8 text-base font-medium text-secondary-foreground transition-all hover:bg-secondary/80"',
    '          >',
    '            Sign In',
    '          </Link>',
    '        </motion.div>',
    '      </div>',
    '    </section>',
    '  );',
    '}',
])

# ── Stats ────────────────────────────────────────────────────────
w("components/stats.tsx", [
    '"use client";',
    '',
    'import { motion } from "framer-motion";',
    '',
    'const stats = [',
    '  { label: "Active Users", value: "50,000+" },',
    '  { label: "Meals Tracked", value: "2.4M+" },',
    '  { label: "AI Insights", value: "100K+" },',
    '  { label: "Avg. Calorie Accuracy", value: "94%" },',
    '];',
    '',
    'export function Stats() {',
    '  return (',
    '    <section className="border-y border-border bg-secondary/30 py-16">',
    '      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">',
    '        <div className="grid grid-cols-2 gap-8 md:grid-cols-4">',
    '          {stats.map((stat, i) => (',
    '            <motion.div',
    '              key={stat.label}',
    '              initial={{ opacity: 0, y: 20 }}',
    '              whileInView={{ opacity: 1, y: 0 }}',
    '              viewport={{ once: true }}',
    '              transition={{ duration: 0.5, delay: i * 0.1 }}',
    '              className="text-center"',
    '            >',
    '              <div className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">',
    '                {stat.value}',
    '              </div>',
    '              <div className="mt-1 text-sm text-muted-foreground">{stat.label}</div>',
    '            </motion.div>',
    '          ))}',
    '        </div>',
    '      </div>',
    '    </section>',
    '  );',
    '}',
])

# ── Features ─────────────────────────────────────────────────────
w("components/features.tsx", [
    '"use client";',
    '',
    'import { motion } from "framer-motion";',
    'import { Camera, Brain, BarChart3, Target, Bell, Shield } from "lucide-react";',
    '',
    'const features = [',
    '  {',
    '    icon: Camera,',
    '    title: "Snap & Track",',
    '    description: "Take a photo of your meal and AI instantly recognizes ingredients and estimates portions.",',
    '  },',
    '  {',
    '    icon: Brain,',
    '    title: "AI Insights",',
    '    description: "Get personalized recommendations based on your eating patterns and health goals.",',
    '  },',
    '  {',
    '    icon: BarChart3,',
    '    title: "Detailed Analytics",',
    '    description: "Track macros, micronutrients, and trends with beautiful interactive charts.",',
    '  },',
    '  {',
    '    icon: Target,',
    '    title: "Goal Setting",',
    '    description: "Set custom calorie, protein, and micronutrient targets tailored to you.",',
    '  },',
    '  {',
    '    icon: Bell,',
    '    title: "Smart Reminders",',
    '    description: "Never miss a meal log with intelligent notifications and habit tracking.",',
    '  },',
    '  {',
    '    icon: Shield,',
    '    title: "Privacy First",',
    '    description: "Your data is encrypted end-to-end. We never share or sell your information.",',
    '  },',
    '];',
    '',
    'export function Features() {',
    '  return (',
    '    <section id="features" className="py-24">',
    '      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">',
    '        <motion.div',
    '          initial={{ opacity: 0, y: 20 }}',
    '          whileInView={{ opacity: 1, y: 0 }}',
    '          viewport={{ once: true }}',
    '          className="text-center"',
    '        >',
    '          <div className="mb-4 inline-flex rounded-full border border-border bg-secondary/50 px-4 py-1 text-sm text-muted-foreground">',
    '            Everything you need',
    '          </div>',
    '          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">',
    '            Powerful Features for',
    '            <br />',
    '            <span className="gradient-text">Better Nutrition</span>',
    '          </h2>',
    '          <p className="mx-auto mt-4 max-w-2xl text-muted-foreground">',
    '            From AI-powered food recognition to detailed analytics, Foodlytics gives you everything you need to reach your health goals.',
    '          </p>',
    '        </motion.div>',
    '',
    '        <div className="mt-16 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">',
    '          {features.map((feature, i) => (',
    '            <motion.div',
    '              key={feature.title}',
    '              initial={{ opacity: 0, y: 20 }}',
    '              whileInView={{ opacity: 1, y: 0 }}',
    '              viewport={{ once: true }}',
    '              transition={{ duration: 0.5, delay: i * 0.1 }}',
    '              className="group rounded-xl border border-border bg-card p-6 transition-all hover:border-primary/30 hover:shadow-elevated"',
    '            >',
    '              <div className="mb-4 inline-flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary">',
    '                <feature.icon className="h-5 w-5" />',
    '              </div>',
    '              <h3 className="mb-2 text-lg font-semibold">{feature.title}</h3>',
    '              <p className="text-sm leading-relaxed text-muted-foreground">{feature.description}</p>',
    '            </motion.div>',
    '          ))}',
    '        </div>',
    '      </div>',
    '    </section>',
    '  );',
    '}',
])

# ── Testimonials ─────────────────────────────────────────────────
w("components/testimonials.tsx", [
    '"use client";',
    '',
    'import { motion } from "framer-motion";',
    'import { Quote } from "lucide-react";',
    '',
    'const testimonials = [',
    '  {',
    '    name: "Sarah Chen",',
    '    role: "Fitness Coach",',
    '    content: "Foodlytics transformed how I track my clients nutrition. The AI recognition is scary accurate.",',
    '  },',
    '  {',
    '    name: "Marcus Johnson",',
    '    role: "Software Engineer",',
    '    content: "I have tried every nutrition app out there. Foodlytics is the first one that actually made me stick with tracking.",',
    '  },',
    '  {',
    '    name: "Elena Rodriguez",',
    '    role: "Nutritionist",',
    '    content: "The detailed analytics and insights are a game-changer for my practice. Highly recommend.",',
    '  },',
    '];',
    '',
    'export function Testimonials() {',
    '  return (',
    '    <section className="border-t border-border bg-secondary/20 py-24">',
    '      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">',
    '        <motion.div',
    '          initial={{ opacity: 0, y: 20 }}',
    '          whileInView={{ opacity: 1, y: 0 }}',
    '          viewport={{ once: true }}',
    '          className="text-center"',
    '        >',
    '          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">',
    '            Loved by <span className="gradient-text">Thousands</span>',
    '          </h2>',
    '          <p className="mx-auto mt-4 max-w-2xl text-muted-foreground">',
    '            Hear what our users have to say about their Foodlytics experience.',
    '          </p>',
    '        </motion.div>',
    '',
    '        <div className="mt-16 grid gap-6 md:grid-cols-3">',
    '          {testimonials.map((t, i) => (',
    '            <motion.div',
    '              key={t.name}',
    '              initial={{ opacity: 0, y: 20 }}',
    '              whileInView={{ opacity: 1, y: 0 }}',
    '              viewport={{ once: true }}',
    '              transition={{ duration: 0.5, delay: i * 0.1 }}',
    '              className="relative rounded-xl border border-border bg-card p-6"',
    '            >',
    '              <Quote className="mb-3 h-6 w-6 text-primary/40" />',
    '              <p className="text-sm leading-relaxed text-muted-foreground">{t.content}</p>',
    '              <div className="mt-4 border-t border-border pt-4">',
    '                <div className="text-sm font-medium">{t.name}</div>',
    '                <div className="text-xs text-muted-foreground">{t.role}</div>',
    '              </div>',
    '            </motion.div>',
    '          ))}',
    '        </div>',
    '      </div>',
    '    </section>',
    '  );',
    '}',
])

# ── Pricing ──────────────────────────────────────────────────────
w("components/pricing.tsx", [
    '"use client";',
    '',
    'import { motion } from "framer-motion";',
    'import { Check } from "lucide-react";',
    'import Link from "next/link";',
    '',
    'const plans = [',
    '  {',
    '    name: "Free",',
    '    price: "$0",',
    '    description: "Perfect for getting started",',
    '    features: ["Basic meal tracking", "AI food recognition (10/day)", "3-day history", "Basic stats"],',
    '    cta: "Get Started",',
    '    href: "/signup",',
    '    featured: false,',
    '  },',
    '  {',
    '    name: "Pro",',
    '    price: "$12",',
    '    period: "/month",',
    '    description: "For serious nutrition tracking",',
    '    features: [',
    '      "Unlimited AI recognition",',
    '      "Full meal history",',
    '      "Detailed macro analytics",',
    '      "Custom goals & targets",',
    '      "Export reports",',
    '      "Priority support",',
    '    ],',
    '    cta: "Start Free Trial",',
    '    href: "/signup",',
    '    featured: true,',
    '  },',
    '  {',
    '    name: "Enterprise",',
    '    price: "$49",',
    '    period: "/month",',
    '    description: "For coaches & professionals",',
    '    features: [',
    '      "Everything in Pro",',
    '      "Client management",',
    '      "Team analytics",',
    '      "API access",',
    '      "White-label options",',
    '      "Dedicated account manager",',
    '    ],',
    '    cta: "Contact Sales",',
    '    href: "/signup",',
    '    featured: false,',
    '  },',
    '];',
    '',
    'export function Pricing() {',
    '  return (',
    '    <section id="pricing" className="py-24">',
    '      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">',
    '        <motion.div',
    '          initial={{ opacity: 0, y: 20 }}',
    '          whileInView={{ opacity: 1, y: 0 }}',
    '          viewport={{ once: true }}',
    '          className="text-center"',
    '        >',
    '          <div className="mb-4 inline-flex rounded-full border border-border bg-secondary/50 px-4 py-1 text-sm text-muted-foreground">',
    '            Simple pricing',
    '          </div>',
    '          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">',
    '            Plans for <span className="gradient-text">Every Goal</span>',
    '          </h2>',
    '          <p className="mx-auto mt-4 max-w-2xl text-muted-foreground">',
    '            Start free and upgrade as your nutrition journey evolves.',
    '          </p>',
    '        </motion.div>',
    '',
    '        <div className="mt-16 grid gap-8 lg:grid-cols-3">',
    '          {plans.map((plan, i) => (',
    '            <motion.div',
    '              key={plan.name}',
    '              initial={{ opacity: 0, y: 20 }}',
    '              whileInView={{ opacity: 1, y: 0 }}',
    '              viewport={{ once: true }}',
    '              transition={{ duration: 0.5, delay: i * 0.1 }}',
    '              className={`relative flex flex-col rounded-2xl border p-8 ${',
    '                plan.featured',
    '                  ? "border-primary bg-card shadow-elevated"',
    '                  : "border-border bg-card"',
    '              }`}',
    '            >',
    '              {plan.featured && (',
    '                <div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-primary px-4 py-1 text-xs font-medium text-primary-foreground">',
    '                  Most Popular',
    '                </div>',
    '              )}',
    '              <div className="mb-6">',
    '                <h3 className="text-lg font-semibold">{plan.name}</h3>',
    '                <div className="mt-2 flex items-baseline gap-1">',
    '                  <span className="text-4xl font-bold">{plan.price}</span>',
    '                  {plan.period && <span className="text-sm text-muted-foreground">{plan.period}</span>}',
    '                </div>',
    '                <p className="mt-2 text-sm text-muted-foreground">{plan.description}</p>',
    '              </div>',
    '              <ul className="mb-8 flex-1 space-y-3">',
    '                {plan.features.map((f) => (',
    '                  <li key={f} className="flex items-start gap-3 text-sm">',
    '                    <Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" />',
    '                    <span className="text-muted-foreground">{f}</span>',
    '                  </li>',
    '                ))}',
    '              </ul>',
    '              <Link',
    '                href={plan.href}',
    '                className={`inline-flex h-11 items-center justify-center rounded-xl text-sm font-medium transition-all ${',
    '                  plan.featured',
    '                    ? "bg-primary text-primary-foreground shadow-lg shadow-primary/25 hover:opacity-90"',
    '                    : "border border-input bg-secondary text-secondary-foreground hover:bg-secondary/80"',
    '                }`}',
    '              >',
    '                {plan.cta}',
    '              </Link>',
    '            </motion.div>',
    '          ))}',
    '        </div>',
    '      </div>',
    '    </section>',
    '  );',
    '}',
])

# ── FAQ ──────────────────────────────────────────────────────────
w("components/faq.tsx", [
    '"use client";',
    '',
    'import { useState } from "react";',
    'import { motion, AnimatePresence } from "framer-motion";',
    'import { ChevronDown } from "lucide-react";',
    '',
    'const faqs = [',
    '  {',
    '    q: "How does the AI food recognition work?",',
    '    a: "Simply take a photo of your meal and our AI analyzes the image to identify ingredients and estimate portion sizes. It uses advanced computer vision trained on millions of food images.",',
    '  },',
    '  {',
    '    q: "Can I track custom recipes?",',
    '    a: "Yes! You can create custom recipes by adding individual ingredients. Foodlytics will calculate the complete nutritional profile for your recipe.",',
    '  },',
    '  {',
    '    q: "Is my data private and secure?",',
    '    a: "Absolutely. All your data is encrypted end-to-end. We follow industry best practices for security and never share your personal information.",',
    '  },',
    '  {',
    '    q: "Can I export my nutrition data?",',
    '    a: "Pro and Enterprise users can export their data as CSV or PDF reports. Enterprise users also get API access for custom integrations.",',
    '  },',
    '  {',
    '    q: "What if I have dietary restrictions?",',
    '    a: "Foodlytics supports various dietary preferences including keto, vegan, vegetarian, paleo, and more. You can set custom macros and micronutrient targets.",',
    '  },',
    '];',
    '',
    'export function FAQ() {',
    '  const [openIndex, setOpenIndex] = useState<number | null>(null);',
    '',
    '  return (',
    '    <section id="faq" className="border-t border-border bg-secondary/20 py-24">',
    '      <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">',
    '        <motion.div',
    '          initial={{ opacity: 0, y: 20 }}',
    '          whileInView={{ opacity: 1, y: 0 }}',
    '          viewport={{ once: true }}',
    '          className="text-center"',
    '        >',
    '          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">',
    '            Frequently Asked <span className="gradient-text">Questions</span>',
    '          </h2>',
    '        </motion.div>',
    '',
    '        <div className="mt-12 space-y-3">',
    '          {faqs.map((faq, i) => (',
    '            <div',
    '              key={i}',
    '              className="rounded-xl border border-border bg-card overflow-hidden"',
    '            >',
    '              <button',
    '                onClick={() => setOpenIndex(openIndex === i ? null : i)}',
    '                className="flex w-full items-center justify-between p-5 text-left transition-colors hover:bg-secondary/50"',
    '              >',
    '                <span className="text-sm font-medium">{faq.q}</span>',
    '                <ChevronDown className={`h-4 w-4 shrink-0 text-muted-foreground transition-transform ${openIndex === i ? "rotate-180" : ""}`} />',
    '              </button>',
    '              <AnimatePresence>',
    '                {openIndex === i && (',
    '                  <motion.div',
    '                    initial={{ height: 0, opacity: 0 }}',
    '                    animate={{ height: "auto", opacity: 1 }}',
    '                    exit={{ height: 0, opacity: 0 }}',
    '                    transition={{ duration: 0.2 }}',
    '                    className="overflow-hidden"',
    '                  >',
    '                    <div className="border-t border-border px-5 pb-5 pt-3 text-sm leading-relaxed text-muted-foreground">',
    '                      {faq.a}',
    '                    </div>',
    '                  </motion.div>',
    '                )}',
    '              </AnimatePresence>',
    '            </div>',
    '          ))}',
    '        </div>',
    '      </div>',
    '    </section>',
    '  );',
    '}',
])

# ── Footer ──────────────────────────────────────────────────────
w("components/footer.tsx", [
    'import Link from "next/link";',
    'import { Leaf } from "lucide-react";',
    '',
    'export function Footer() {',
    '  return (',
    '    <footer className="border-t border-border bg-card">',
    '      <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">',
    '        <div className="flex flex-col items-center justify-between gap-6 md:flex-row">',
    '          <div className="flex items-center gap-2">',
    '            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary">',
    '              <Leaf className="h-3.5 w-3.5 text-primary-foreground" />',
    '            </div>',
    '            <span className="text-sm font-bold">Foodlytics</span>',
    '          </div>',
    '          <nav className="flex gap-6">',
    '            <Link href="#features" className="text-xs text-muted-foreground transition-colors hover:text-foreground">Features</Link>',
    '            <Link href="#pricing" className="text-xs text-muted-foreground transition-colors hover:text-foreground">Pricing</Link>',
    '            <Link href="#faq" className="text-xs text-muted-foreground transition-colors hover:text-foreground">FAQ</Link>',
    '          </nav>',
    '          <p className="text-xs text-muted-foreground">',
    '            &copy; {new Date().getFullYear()} Foodlytics. All rights reserved.',
    '          </p>',
    '        </div>',
    '      </div>',
    '    </footer>',
    '  );',
    '}',
])

# ── Landing Page ─────────────────────────────────────────────────
w("app/page.tsx", [
    'import { Header } from "@/components/header";',
    'import { Hero } from "@/components/hero";',
    'import { Stats } from "@/components/stats";',
    'import { Features } from "@/components/features";',
    'import { Testimonials } from "@/components/testimonials";',
    'import { Pricing } from "@/components/pricing";',
    'import { FAQ } from "@/components/faq";',
    'import { Footer } from "@/components/footer";',
    '',
    'export default function Home() {',
    '  return (',
    '    <>',
    '      <Header />',
    '      <Hero />',
    '      <Stats />',
    '      <Features />',
    '      <Testimonials />',
    '      <Pricing />',
    '      <FAQ />',
    '      <Footer />',
    '    </>',
    '  );',
    '}',
])

# ── Root Layout ──────────────────────────────────────────────────
w("app/layout.tsx", [
    'import type { Metadata } from "next";',
    'import { Geist, Geist_Mono } from "next/font/google";',
    'import { ThemeProvider } from "@/components/theme-provider";',
    'import "./globals.css";',
    '',
    'const geistSans = Geist({',
    '  variable: "--font-geist-sans",',
    '  subsets: ["latin"],',
    '});',
    '',
    'const geistMono = Geist_Mono({',
    '  variable: "--font-geist-mono",',
    '  subsets: ["latin"],',
    '});',
    '',
    'export const metadata: Metadata = {',
    '  title: "Foodlytics - AI-Powered Nutrition Tracking",',
    '  description: "Track your nutrition with AI-powered insights and personalized recommendations.",',
    '};',
    '',
    'export default function RootLayout({',
    '  children,',
    '}: Readonly<{',
    '  children: React.ReactNode;',
    '}>) {',
    '  return (',
    '    <html',
    '      lang="en"',
    '      className={`${geistSans.variable} ${geistMono.variable}`}',
    '      suppressHydrationWarning',
    '    >',
    '      <body className="min-h-screen bg-background font-sans antialiased">',
    '        <ThemeProvider>{children}</ThemeProvider>',
    '      </body>',
    '    </html>',
    '  );',
    '}',
])

# ── Auth Layout (route group) ────────────────────────────────────
w("app/(auth)/layout.tsx", [
    'export default function AuthLayout({',
    '  children,',
    '}: {',
    '  children: React.ReactNode;',
    '}) {',
    '  return <>{children}</>;',
    '}',
])

# ── Login Page (split-screen) ────────────────────────────────────
w("app/(auth)/login/page.tsx", [
    '"use client";',
    '',
    'import { useActionState } from "react";',
    'import { login } from "@/app/actions/auth";',
    'import Link from "next/link";',
    'import { Leaf, Loader2 } from "lucide-react";',
    '',
    'export default function LoginPage() {',
    '  const [state, formAction, pending] = useActionState(login, undefined);',
    '',
    '  return (',
    '    <div className="flex min-h-screen">',
    '      {/* Brand side */}',
    '      <div className="relative hidden w-1/2 flex-col items-center justify-center bg-gradient-to-br from-primary/20 via-background to-primary/5 p-12 lg:flex">',
    '        <div className="relative z-10 max-w-md text-center">',
    '          <div className="mx-auto mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-primary shadow-xl shadow-primary/25">',
    '            <Leaf className="h-8 w-8 text-primary-foreground" />',
    '          </div>',
    '          <h2 className="mb-3 text-3xl font-bold tracking-tight">Welcome Back</h2>',
    '          <p className="text-muted-foreground">',
    '            Continue your nutrition journey. Track meals, analyze patterns, and optimize your health with AI-powered insights.',
    '          </p>',
    '          <div className="mt-8 rounded-xl border border-border bg-card/50 p-6 text-left">',
    '            <div className="mb-2 text-sm font-medium">Pro Tip</div>',
    '            <p className="text-xs leading-relaxed text-muted-foreground">',
    '              Consistent tracking is the key to success. Try to log your meals within 30 minutes of eating for the most accurate AI recognition.',
    '            </p>',
    '          </div>',
    '        </div>',
    '      </div>',
    '',
    '      {/* Form side */}',
    '      <div className="flex w-full items-center justify-center p-8 lg:w-1/2">',
    '        <div className="w-full max-w-sm">',
    '          <div className="mb-8">',
    '            <Link href="/" className="mb-8 flex items-center gap-2">',
    '              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary">',
    '                <Leaf className="h-4 w-4 text-primary-foreground" />',
    '              </div>',
    '              <span className="text-lg font-bold">Foodlytics</span>',
    '            </Link>',
    '            <h1 className="mt-8 text-2xl font-bold tracking-tight">Sign in</h1>',
    '            <p className="mt-1 text-sm text-muted-foreground">',
    '              Enter your email and password to access your account.',
    '            </p>',
    '          </div>',
    '',
    '          <form action={formAction} className="space-y-4">',
    '            <div>',
    '              <label htmlFor="email" className="block text-sm font-medium mb-1.5">',
    '                Email',
    '              </label>',
    '              <input',
    '                id="email"',
    '                name="email"',
    '                type="email"',
    '                placeholder="you@example.com"',
    '                required',
    '                className="w-full rounded-lg border border-input bg-background px-3 py-2.5 text-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-ring focus:ring-1 focus:ring-ring"',
    '              />',
    '            </div>',
    '',
    '            <div>',
    '              <label htmlFor="password" className="block text-sm font-medium mb-1.5">',
    '                Password',
    '              </label>',
    '              <input',
    '                id="password"',
    '                name="password"',
    '                type="password"',
    '                placeholder="Enter your password"',
    '                required',
    '                className="w-full rounded-lg border border-input bg-background px-3 py-2.5 text-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-ring focus:ring-1 focus:ring-ring"',
    '              />',
    '            </div>',
    '',
    '            {state?.error && (',
    '              <div className="rounded-lg bg-destructive/10 px-3 py-2 text-sm text-destructive">',
    '                {state.error}',
    '              </div>',
    '            )}',
    '',
    '            <button',
    '              type="submit"',
    '              disabled={pending}',
    '              className="inline-flex h-11 w-full items-center justify-center rounded-lg bg-primary text-sm font-medium text-primary-foreground shadow-lg shadow-primary/25 transition-all hover:opacity-90 disabled:opacity-50"',
    '            >',
    '              {pending ? <Loader2 className="h-4 w-4 animate-spin" /> : "Sign in"}',
    '            </button>',
    '          </form>',
    '',
    '          <p className="mt-6 text-center text-sm text-muted-foreground">',
    '            Do not have an account?{" "}',
    '            <Link href="/signup" className="font-medium text-primary hover:underline">',
    '              Sign up',
    '            </Link>',
    '          </p>',
    '        </div>',
    '      </div>',
    '    </div>',
    '  );',
    '}',
])

# ── Signup Page (split-screen) ────────────────────────────────
w("app/(auth)/signup/page.tsx", [
    '"use client";',
    '',
    'import { useActionState } from "react";',
    'import { signup } from "@/app/actions/auth";',
    'import Link from "next/link";',
    'import { Leaf, Loader2 } from "lucide-react";',
    '',
    'export default function SignupPage() {',
    '  const [state, formAction, pending] = useActionState(signup, undefined);',
    '',
    '  return (',
    '    <div className="flex min-h-screen">',
    '      {/* Brand side */}',
    '      <div className="relative hidden w-1/2 flex-col items-center justify-center bg-gradient-to-br from-primary/20 via-background to-primary/5 p-12 lg:flex">',
    '        <div className="relative z-10 max-w-md text-center">',
    '          <div className="mx-auto mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-primary shadow-xl shadow-primary/25">',
    '            <Leaf className="h-8 w-8 text-primary-foreground" />',
    '          </div>',
    '          <h2 className="mb-3 text-3xl font-bold tracking-tight">Start Your Journey</h2>',
    '          <p className="text-muted-foreground">',
    '            Join thousands of users who have transformed their nutrition habits with AI-powered tracking and insights.',
    '          </p>',
    '          <div className="mt-8 grid grid-cols-2 gap-4 text-left">',
    '            <div className="rounded-xl border border-border bg-card/50 p-4">',
    '              <div className="text-2xl font-bold text-primary">50K+</div>',
    '              <div className="text-xs text-muted-foreground">Active Users</div>',
    '            </div>',
    '            <div className="rounded-xl border border-border bg-card/50 p-4">',
    '              <div className="text-2xl font-bold text-primary">2.4M+</div>',
    '              <div className="text-xs text-muted-foreground">Meals Tracked</div>',
    '            </div>',
    '          </div>',
    '        </div>',
    '      </div>',
    '',
    '      {/* Form side */}',
    '      <div className="flex w-full items-center justify-center p-8 lg:w-1/2">',
    '        <div className="w-full max-w-sm">',
    '          <div className="mb-8">',
    '            <Link href="/" className="mb-8 flex items-center gap-2">',
    '              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary">',
    '                <Leaf className="h-4 w-4 text-primary-foreground" />',
    '              </div>',
    '              <span className="text-lg font-bold">Foodlytics</span>',
    '            </Link>',
    '            <h1 className="mt-8 text-2xl font-bold tracking-tight">Create an account</h1>',
    '            <p className="mt-1 text-sm text-muted-foreground">',
    '              Start tracking your nutrition with AI-powered insights.',
    '            </p>',
    '          </div>',
    '',
    '          <form action={formAction} className="space-y-4">',
    '            <div>',
    '              <label htmlFor="full_name" className="block text-sm font-medium mb-1.5">',
    '                Full Name',
    '              </label>',
    '              <input',
    '                id="full_name"',
    '                name="full_name"',
    '                type="text"',
    '                placeholder="John Doe"',
    '                required',
    '                className="w-full rounded-lg border border-input bg-background px-3 py-2.5 text-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-ring focus:ring-1 focus:ring-ring"',
    '              />',
    '            </div>',
    '',
    '            <div>',
    '              <label htmlFor="email" className="block text-sm font-medium mb-1.5">',
    '                Email',
    '              </label>',
    '              <input',
    '                id="email"',
    '                name="email"',
    '                type="email"',
    '                placeholder="you@example.com"',
    '                required',
    '                className="w-full rounded-lg border border-input bg-background px-3 py-2.5 text-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-ring focus:ring-1 focus:ring-ring"',
    '              />',
    '            </div>',
    '',
    '            <div>',
    '              <label htmlFor="password" className="block text-sm font-medium mb-1.5">',
    '                Password',
    '              </label>',
    '              <input',
    '                id="password"',
    '                name="password"',
    '                type="password"',
    '                placeholder="Create a strong password"',
    '                required',
    '                className="w-full rounded-lg border border-input bg-background px-3 py-2.5 text-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-ring focus:ring-1 focus:ring-ring"',
    '              />',
    '            </div>',
    '',
    '            {state?.error && (',
    '              <div className="rounded-lg bg-destructive/10 px-3 py-2 text-sm text-destructive">',
    '                {state.error}',
    '              </div>',
    '            )}',
    '',
    '            {state?.success && (',
    '              <div className="rounded-lg bg-primary/10 px-3 py-2 text-sm text-primary">',
    '                {state.success}',
    '              </div>',
    '            )}',
    '',
    '            <button',
    '              type="submit"',
    '              disabled={pending}',
    '              className="inline-flex h-11 w-full items-center justify-center rounded-lg bg-primary text-sm font-medium text-primary-foreground shadow-lg shadow-primary/25 transition-all hover:opacity-90 disabled:opacity-50"',
    '            >',
    '              {pending ? <Loader2 className="h-4 w-4 animate-spin" /> : "Create account"}',
    '            </button>',
    '          </form>',
    '',
    '          <p className="mt-6 text-center text-sm text-muted-foreground">',
    '            Already have an account?{" "}',
    '            <Link href="/login" className="font-medium text-primary hover:underline">',
    '              Sign in',
    '            </Link>',
    '          </p>',
    '        </div>',
    '      </div>',
    '    </div>',
    '  );',
    '}',
])

# ── Dashboard Layout ─────────────────────────────────────────────
w("app/dashboard/layout.tsx", [
    'import { Sidebar } from "@/components/sidebar";',
    '',
    'export default function DashboardLayout({',
    '  children,',
    '}: {',
    '  children: React.ReactNode;',
    '}) {',
    '  return (',
    '    <div className="flex min-h-screen">',
    '      <Sidebar />',
    '      <main className="flex-1 overflow-y-auto bg-background lg:pl-64">',
    '        {children}',
    '      </main>',
    '    </div>',
    '  );',
    '}',
])

# ── Sidebar ──────────────────────────────────────────────────────
w("components/sidebar.tsx", [
    '"use client";',
    '',
    'import Link from "next/link";',
    'import { usePathname } from "next/navigation";',
    'import {',
    '  Leaf,',
    '  LayoutDashboard,',
    '  UtensilsCrossed,',
    '  BarChart3,',
    '  Target,',
    '  Settings,',
    '  LogOut,',
    '  Menu,',
    '  X,',
    '} from "lucide-react";',
    'import { useState } from "react";',
    'import { logout } from "@/app/actions/auth";',
    'import { ThemeToggle } from "@/components/theme-toggle";',
    '',
    'const navItems = [',
    '  { href: "/dashboard", label: "Dashboard", icon: LayoutDashboard },',
    '  { href: "/dashboard/meals", label: "Meals", icon: UtensilsCrossed },',
    '  { href: "/dashboard/analytics", label: "Analytics", icon: BarChart3 },',
    '  { href: "/dashboard/goals", label: "Goals", icon: Target },',
    '  { href: "/dashboard/settings", label: "Settings", icon: Settings },',
    '];',
    '',
    'export function Sidebar() {',
    '  const pathname = usePathname();',
    '  const [mobileOpen, setMobileOpen] = useState(false);',
    '',
    '  return (',
    '    <>',
    '      {/* Mobile toggle */}',
    '      <button',
    '        onClick={() => setMobileOpen(!mobileOpen)}',
    '        className="fixed left-4 top-4 z-50 flex h-9 w-9 items-center justify-center rounded-lg border border-border bg-background lg:hidden"',
    '      >',
    '        {mobileOpen ? <X className="h-4 w-4" /> : <Menu className="h-4 w-4" />}',
    '      </button>',
    '',
    '      {/* Overlay */}',
    '      {mobileOpen && (',
    '        <div',
    '          className="fixed inset-0 z-30 bg-black/50 lg:hidden"',
    '          onClick={() => setMobileOpen(false)}',
    '        />',
    '      )}',
    '',
    '      {/* Sidebar */}',
    '      <aside',
    '        className={`fixed inset-y-0 left-0 z-40 flex w-64 flex-col border-r border-border bg-sidebar transition-transform lg:translate-x-0 ${mobileOpen ? "translate-x-0" : "-translate-x-full"}`}',
    '      >',
    '        {/* Logo */}',
    '        <div className="flex h-16 items-center gap-2 border-b border-border/50 px-6">',
    '          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary">',
    '            <Leaf className="h-4 w-4 text-primary-foreground" />',
    '          </div>',
    '          <span className="text-lg font-bold text-sidebar-foreground">Foodlytics</span>',
    '        </div>',
    '',
    '        {/* Navigation */}',
    '        <nav className="flex-1 space-y-1 p-4">',
    '          {navItems.map((item) => {',
    '            const isActive = pathname === item.href;',
    '            return (',
    '              <Link',
    '                key={item.href}',
    '                href={item.href}',
    '                onClick={() => setMobileOpen(false)}',
    '                className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors ${isActive ? "bg-sidebar-accent text-white" : "text-sidebar-muted hover:bg-sidebar-muted/10 hover:text-sidebar-foreground"}`}',
    '              >',
    '                <item.icon className="h-4 w-4 shrink-0" />',
    '                {item.label}',
    '              </Link>',
    '            );',
    '          })}',
    '        </nav>',
    '',
    '        {/* Bottom */}',
    '        <div className="border-t border-border/50 p-4">',
    '          <div className="mb-3 flex items-center justify-between">',
    '            <span className="text-xs text-sidebar-muted">Theme</span>',
    '            <ThemeToggle />',
    '          </div>',
    '          <form action={logout}>',
    '            <button',
    '              type="submit"',
    '              className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-sidebar-muted transition-colors hover:bg-sidebar-muted/10 hover:text-sidebar-foreground"',
    '            >',
    '              <LogOut className="h-4 w-4 shrink-0" />',
    '              Sign Out',
    '            </button>',
    '          </form>',
    '        </div>',
    '      </aside>',
    '    </>',
    '  );',
    '}',
])

# ── Dashboard Page ──────────────────────────────────────────────
w("app/dashboard/page.tsx", [
    'import { createClient } from "@/lib/supabase/server";',
    'import { redirect } from "next/navigation";',
    'import { UtensilsCrossed, Flame, Apple } from "lucide-react";',
    '',
    'export default async function DashboardPage() {',
    '  const supabase = await createClient();',
    '  const { data, error } = await supabase.auth.getUser();',
    '',
    '  if (error || !data?.user) {',
    '    redirect("/login");',
    '  }',
    '',
    '  const user = data.user;',
    '',
    '  return (',
    '    <div className="p-6 lg:p-8">',
    '      {/* Header */}',
    '      <div className="mb-8">',
    '        <h1 className="text-2xl font-bold tracking-tight">',
    '          Welcome, {user.user_metadata?.full_name || "there"}',
    '        </h1>',
    '        <p className="text-sm text-muted-foreground">',
    '          Here is your nutrition overview for today.',
    '        </p>',
    '      </div>',
    '',
    '      {/* Stats grid */}',
    '      <div className="mb-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">',
    '        <div className="rounded-xl border border-border bg-card p-5 transition-all hover:shadow-elevated">',
    '          <div className="mb-3 flex items-center justify-between">',
    '            <span className="text-sm font-medium text-muted-foreground">Calories</span>',
    '            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary">',
    '              <Flame className="h-4 w-4" />',
    '            </div>',
    '          </div>',
    '          <div className="text-3xl font-bold tracking-tight">--</div>',
    '          <div className="mt-1 text-xs text-muted-foreground">of 2,000 goal</div>',
    '        </div>',
    '',
    '        <div className="rounded-xl border border-border bg-card p-5 transition-all hover:shadow-elevated">',
    '          <div className="mb-3 flex items-center justify-between">',
    '            <span className="text-sm font-medium text-muted-foreground">Protein</span>',
    '            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary">',
    '              <Apple className="h-4 w-4" />',
    '            </div>',
    '          </div>',
    '          <div className="text-3xl font-bold tracking-tight">--</div>',
    '          <div className="mt-1 text-xs text-muted-foreground">of 150g goal</div>',
    '        </div>',
    '',
    '        <div className="rounded-xl border border-border bg-card p-5 transition-all hover:shadow-elevated">',
    '          <div className="mb-3 flex items-center justify-between">',
    '            <span className="text-sm font-medium text-muted-foreground">Meals Logged</span>',
    '            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary">',
    '              <UtensilsCrossed className="h-4 w-4" />',
    '            </div>',
    '          </div>',
    '          <div className="text-3xl font-bold tracking-tight">0</div>',
    '          <div className="mt-1 text-xs text-muted-foreground">meals today</div>',
    '        </div>',
    '      </div>',
    '',
    '      {/* Recent meals placeholder */}',
    '      <div className="rounded-xl border border-border bg-card p-6">',
    '        <h2 className="mb-4 text-lg font-semibold">Recent Meals</h2>',
    '        <div className="flex flex-col items-center justify-center py-12 text-center">',
    '          <UtensilsCrossed className="mb-3 h-8 w-8 text-muted-foreground/40" />',
    '          <p className="text-sm text-muted-foreground">No meals logged yet today.</p>',
    '          <p className="text-xs text-muted-foreground/60">',
    '            Start tracking your nutrition to see your meals here.',
    '          </p>',
    '        </div>',
    '      </div>',
    '    </div>',
    '  );',
    '}',
])

print("\nAll files written successfully!")